export const searchItems = [
  'Weather',
  'track UPS package',
  'name of movie movie',
  'restaurant name restaurant near me',
  'Flights to location',
  'hotels near me',
  'my shopping list',
  'lyrics to song name',
  'check symptoms for flu',
  'check latest news',
  'grocery list',
  'my grocery list',
  'the meaning of insert word',
  'US Elections',
  'stock market',
  'game results',
  'video games',
];
